version: '2'

services:
  mariadb:
    container_name: hbv_db
    image: docker.io/bitnami/mariadb:10.6
    restart: unless-stopped
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_PASSWORD=hbvpass
      - MARIADB_USER=hbvpass
      - MARIADB_DATABASE=hbv
    ports:
      - '3306:3306'
    volumes:
      - './db:/bitnami/mariadb'
      - './db/sql:/docker-entrypoint-initdb.d'
  myapp:
    image: docker.io/bitnami/symfony:6.1
    container_name: hbv_app
    ports:
      - '4000:8000'
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE_HOST=mariadb
      - MARIADB_DATABASE_PORT_NUMBER=3306
      - MARIADB_DATABASE_USER=hbvpass
      - MARIADB_DATABASE_PASSWORD=hbvpass
      - MARIADB_DATABASE_NAME=hbv
      - SYMFONY_PROJECT_NAME=hbv
    volumes:
      - './src:/app'
    depends_on:
      - mariadb
